# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 44ebdaa1db4bf04f1ff60fc7ff4290b7c468b35e49e3836c85a9101165a3f21a90309e71a77d4cec6985ca6d6c6367b9c238e96e88f1e5b362a97650b2dd8d21

test:
  secret_key_base: eee47edcdd028f58adc36b1465285f5c6d10db9303a5908943b8de6108dbae30a777d44b77872f557f99d3e6483178cea39c59f2f18692bfaf36554431f07af2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
